---
- name: install softwares
  hosts: ubuntu
  vars:
    package_list:
      - nginx
      - default-jdk
      - apache2
      - mysql-server
  tasks:
    - name: install softwares
      apt:
        name: "{{ item }}" #ref name mentioned in vars
        state: present
        update_cache: yes
      loop: "{{ package_list }}" #iterate
